spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: haenaem
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  transaction:
    default-timeout: 30

haenaem:
  storage:
    type: s3
    s3:
      access-key: ${AWS_S3_ACCESS_KEY} #Github secret? ?? ??
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION}

logging:
  level:
    root: INFO

